/********************************************************************
LC			10/14/2016
Created:	8/16/2016
Filename:	soApiDefines.h 
Author:		Lehi Muñoz

Purpose:	Cabecera que incluye las definiciones propias de la
			abstraccion de directx
*********************************************************************/
#pragma once
#pragma warning(disable : 4005)

#include <DXGI.h>
#include <D3D11.h>
#include <D3DX11async.h>
#include <d3dcompiler.h>
#include "Soul_Core.h"

namespace SoulSDK
{	
	typedef
		enum API_USAGE
	{
		API_USAGE_DEFAULT = 0,
		API_USAGE_IMMUTABLE = 1,
		API_USAGE_DYNAMIC = 2,
		API_USAGE_STAGING = 3
	} 	API_USAGE;

	typedef
		enum API_BIND_FLAG
	{
		API_BIND_VERTEX_BUFFER = 0x1L,
		API_BIND_INDEX_BUFFER = 0x2L,
		API_BIND_CONSTANT_BUFFER = 0x4L,
		API_BIND_SHADER_RESOURCE = 0x8L,
		API_BIND_STREAM_OUTPUT = 0x10L,
		API_BIND_RENDER_TARGET = 0x20L,
		API_BIND_DEPTH_STENCIL = 0x40L,
		API_BIND_UNORDERED_ACCESS = 0x80L
	} API_BIND_FLAG;

	typedef
		enum API_DSV_DIMENSION
	{
		API_DSV_DIMENSION_UNKNOWN = 0,
		API_DSV_DIMENSION_TEXTURE1D = 1,
		API_DSV_DIMENSION_TEXTURE1DARRAY = 2,
		API_DSV_DIMENSION_TEXTURE2D = 3,
		API_DSV_DIMENSION_TEXTURE2DARRAY = 4,
		API_DSV_DIMENSION_TEXTURE2DMS = 5,
		API_DSV_DIMENSION_TEXTURE2DMSARRAY = 6
	} 	API_DSV_DIMENSION;

	typedef
		enum API_DEPTH_WRITE_MASK
	{
		API_DEPTH_WRITE_MASK_ZERO = 0,
		API_DEPTH_WRITE_MASK_ALL = 1
	} 	API_DEPTH_WRITE_MASK;

	typedef
		enum API_COMPARISON_FUNC
	{
		API_COMPARISON_NEVER = 1,
		API_COMPARISON_LESS = 2,
		API_COMPARISON_EQUAL = 3,
		API_COMPARISON_LESS_EQUAL = 4,
		API_COMPARISON_GREATER = 5,
		API_COMPARISON_NOT_EQUAL = 6,
		API_COMPARISON_GREATER_EQUAL = 7,
		API_COMPARISON_ALWAYS = 8
	} 	API_COMPARISON_FUNC;

	typedef
		enum API_RESOURCE_MISC_FLAG
	{
		API_RESOURCE_MISC_GENERATE_MIPS = 0x1L,
		API_RESOURCE_MISC_SHARED = 0x2L,
		API_RESOURCE_MISC_TEXTURECUBE = 0x4L,
		API_RESOURCE_MISC_DRAWINDIRECT_ARGS = 0x10L,
		API_RESOURCE_MISC_BUFFER_ALLOW_RAW_VIEWS = 0x20L,
		API_RESOURCE_MISC_BUFFER_STRUCTURED = 0x40L,
		API_RESOURCE_MISC_RESOURCE_CLAMP = 0x80L,
		API_RESOURCE_MISC_SHARED_KEYEDMUTEX = 0x100L,
		API_RESOURCE_MISC_GDI_COMPATIBLE = 0x200L
	} 	API_RESOURCE_MISC_FLAG;


	typedef enum APIGI_FORMAT
	{
		APIGI_FORMAT_UNKNOWN = 0,
		APIGI_FORMAT_R32G32B32A32_TYPELESS = 1,
		APIGI_FORMAT_R32G32B32A32_FLOAT = 2,
		APIGI_FORMAT_R32G32B32A32_UINT = 3,
		APIGI_FORMAT_R32G32B32A32_SINT = 4,
		APIGI_FORMAT_R32G32B32_TYPELESS = 5,
		APIGI_FORMAT_R32G32B32_FLOAT = 6,
		APIGI_FORMAT_R32G32B32_UINT = 7,
		APIGI_FORMAT_R32G32B32_SINT = 8,
		APIGI_FORMAT_R16G16B16A16_TYPELESS = 9,
		APIGI_FORMAT_R16G16B16A16_FLOAT = 10,
		APIGI_FORMAT_R16G16B16A16_UNORM = 11,
		APIGI_FORMAT_R16G16B16A16_UINT = 12,
		APIGI_FORMAT_R16G16B16A16_SNORM = 13,
		APIGI_FORMAT_R16G16B16A16_SINT = 14,
		APIGI_FORMAT_R32G32_TYPELESS = 15,
		APIGI_FORMAT_R32G32_FLOAT = 16,
		APIGI_FORMAT_R32G32_UINT = 17,
		APIGI_FORMAT_R32G32_SINT = 18,
		APIGI_FORMAT_R32G8X24_TYPELESS = 19,
		APIGI_FORMAT_D32_FLOAT_S8X24_UINT = 20,
		APIGI_FORMAT_R32_FLOAT_X8X24_TYPELESS = 21,
		APIGI_FORMAT_X32_TYPELESS_G8X24_UINT = 22,
		APIGI_FORMAT_R10G10B10A2_TYPELESS = 23,
		APIGI_FORMAT_R10G10B10A2_UNORM = 24,
		APIGI_FORMAT_R10G10B10A2_UINT = 25,
		APIGI_FORMAT_R11G11B10_FLOAT = 26,
		APIGI_FORMAT_R8G8B8A8_TYPELESS = 27,
		APIGI_FORMAT_R8G8B8A8_UNORM = 28,
		APIGI_FORMAT_R8G8B8A8_UNORM_SRGB = 29,
		APIGI_FORMAT_R8G8B8A8_UINT = 30,
		APIGI_FORMAT_R8G8B8A8_SNORM = 31,
		APIGI_FORMAT_R8G8B8A8_SINT = 32,
		APIGI_FORMAT_R16G16_TYPELESS = 33,
		APIGI_FORMAT_R16G16_FLOAT = 34,
		APIGI_FORMAT_R16G16_UNORM = 35,
		APIGI_FORMAT_R16G16_UINT = 36,
		APIGI_FORMAT_R16G16_SNORM = 37,
		APIGI_FORMAT_R16G16_SINT = 38,
		APIGI_FORMAT_R32_TYPELESS = 39,
		APIGI_FORMAT_D32_FLOAT = 40,
		APIGI_FORMAT_R32_FLOAT = 41,
		APIGI_FORMAT_R32_UINT = 42,
		APIGI_FORMAT_R32_SINT = 43,
		APIGI_FORMAT_R24G8_TYPELESS = 44,
		APIGI_FORMAT_D24_UNORM_S8_UINT = 45,
		APIGI_FORMAT_R24_UNORM_X8_TYPELESS = 46,
		APIGI_FORMAT_X24_TYPELESS_G8_UINT = 47,
		APIGI_FORMAT_R8G8_TYPELESS = 48,
		APIGI_FORMAT_R8G8_UNORM = 49,
		APIGI_FORMAT_R8G8_UINT = 50,
		APIGI_FORMAT_R8G8_SNORM = 51,
		APIGI_FORMAT_R8G8_SINT = 52,
		APIGI_FORMAT_R16_TYPELESS = 53,
		APIGI_FORMAT_R16_FLOAT = 54,
		APIGI_FORMAT_D16_UNORM = 55,
		APIGI_FORMAT_R16_UNORM = 56,
		APIGI_FORMAT_R16_UINT = 57,
		APIGI_FORMAT_R16_SNORM = 58,
		APIGI_FORMAT_R16_SINT = 59,
		APIGI_FORMAT_R8_TYPELESS = 60,
		APIGI_FORMAT_R8_UNORM = 61,
		APIGI_FORMAT_R8_UINT = 62,
		APIGI_FORMAT_R8_SNORM = 63,
		APIGI_FORMAT_R8_SINT = 64,
		APIGI_FORMAT_A8_UNORM = 65,
		APIGI_FORMAT_R1_UNORM = 66,
		APIGI_FORMAT_R9G9B9E5_SHAREDEXP = 67,
		APIGI_FORMAT_R8G8_B8G8_UNORM = 68,
		APIGI_FORMAT_G8R8_G8B8_UNORM = 69,
		APIGI_FORMAT_BC1_TYPELESS = 70,
		APIGI_FORMAT_BC1_UNORM = 71,
		APIGI_FORMAT_BC1_UNORM_SRGB = 72,
		APIGI_FORMAT_BC2_TYPELESS = 73,
		APIGI_FORMAT_BC2_UNORM = 74,
		APIGI_FORMAT_BC2_UNORM_SRGB = 75,
		APIGI_FORMAT_BC3_TYPELESS = 76,
		APIGI_FORMAT_BC3_UNORM = 77,
		APIGI_FORMAT_BC3_UNORM_SRGB = 78,
		APIGI_FORMAT_BC4_TYPELESS = 79,
		APIGI_FORMAT_BC4_UNORM = 80,
		APIGI_FORMAT_BC4_SNORM = 81,
		APIGI_FORMAT_BC5_TYPELESS = 82,
		APIGI_FORMAT_BC5_UNORM = 83,
		APIGI_FORMAT_BC5_SNORM = 84,
		APIGI_FORMAT_B5G6R5_UNORM = 85,
		APIGI_FORMAT_B5G5R5A1_UNORM = 86,
		APIGI_FORMAT_B8G8R8A8_UNORM = 87,
		APIGI_FORMAT_B8G8R8X8_UNORM = 88,
		APIGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM = 89,
		APIGI_FORMAT_B8G8R8A8_TYPELESS = 90,
		APIGI_FORMAT_B8G8R8A8_UNORM_SRGB = 91,
		APIGI_FORMAT_B8G8R8X8_TYPELESS = 92,
		APIGI_FORMAT_B8G8R8X8_UNORM_SRGB = 93,
		APIGI_FORMAT_BC6H_TYPELESS = 94,
		APIGI_FORMAT_BC6H_UF16 = 95,
		APIGI_FORMAT_BC6H_SF16 = 96,
		APIGI_FORMAT_BC7_TYPELESS = 97,
		APIGI_FORMAT_BC7_UNORM = 98,
		APIGI_FORMAT_BC7_UNORM_SRGB = 99,
		APIGI_FORMAT_FORCE_UINT = 0xffffffff
	} APIGI_FORMAT;

#define APIGI_USAGE_SHADER_INPUT             ( 1L << (0 + 4) )
#define APIGI_USAGE_RENDER_TARGET_OUTPUT     ( 1L << (1 + 4) )
#define APIGI_USAGE_BACK_BUFFER              ( 1L << (2 + 4) )
#define APIGI_USAGE_SHARED                   ( 1L << (3 + 4) )
#define APIGI_USAGE_READ_ONLY                ( 1L << (4 + 4) )
#define APIGI_USAGE_DISCARD_ON_PRESENT       ( 1L << (5 + 4) )
#define APIGI_USAGE_UNORDERED_ACCESS         ( 1L << (6 + 4) )
	typedef uint32 APIGI_USAGE;

	typedef
		enum APIGI_SWAP_EFFECT
	{
		APIGI_SWAP_EFFECT_DISCARD = 0,
		APIGI_SWAP_EFFECT_SEQUENTIAL = 1
	} 	APIGI_SWAP_EFFECT;

	typedef
		enum API_FILL_MODE
	{
		API_FILL_WIREFRAME = 2,
		API_FILL_SOLID = 3
	} 	API_FILL_MODE;

	typedef
		enum API_CULL_MODE
	{
		API_CULL_NONE = 1,
		API_CULL_FRONT = 2,
		API_CULL_BACK = 3
	} 	API_CULL_MODE;

	typedef
		enum API_TEXTURE_ADDRESS_MODE
	{
		API_TEXTURE_ADDRESS_WRAP = 1,
		API_TEXTURE_ADDRESS_MIRROR = 2,
		API_TEXTURE_ADDRESS_CLAMP = 3,
		API_TEXTURE_ADDRESS_BORDER = 4,
		API_TEXTURE_ADDRESS_MIRROR_ONCE = 5
	} 	API_TEXTURE_ADDRESS_MODE;

	typedef
		enum API_FILTER
	{
		API_FILTER_MIN_MAG_MIP_POINT = 0,
		API_FILTER_MIN_MAG_POINT_MIP_LINEAR = 0x1,
		API_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x4,
		API_FILTER_MIN_POINT_MAG_MIP_LINEAR = 0x5,
		API_FILTER_MIN_LINEAR_MAG_MIP_POINT = 0x10,
		API_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x11,
		API_FILTER_MIN_MAG_LINEAR_MIP_POINT = 0x14,
		API_FILTER_MIN_MAG_MIP_LINEAR = 0x15,
		API_FILTER_ANISOTROPIC = 0x55,
		API_FILTER_COMPARISON_MIN_MAG_MIP_POINT = 0x80,
		API_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR = 0x81,
		API_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x84,
		API_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR = 0x85,
		API_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT = 0x90,
		API_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x91,
		API_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT = 0x94,
		API_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR = 0x95,
		API_FILTER_COMPARISON_ANISOTROPIC = 0xd5
	} 	API_FILTER;

	typedef struct API_SUBRESOURCE_DATA
	{
		const void *pSysMem;
		uint32 SysMemPitch;
		uint32 SysMemSlicePitch;
	} 	API_SUBRESOURCE_DATA;

	typedef
		enum API_CPU_ACCESS_FLAG
	{
		API_CPU_ACCESS_WRITE = 0x10000L,
		API_CPU_ACCESS_READ = 0x20000L
	} 	API_CPU_ACCESS_FLAG;

	typedef
		enum API_STENCIL_OP
	{
		API_STENCIL_OP_KEEP = 1,
		API_STENCIL_OP_ZERO = 2,
		API_STENCIL_OP_REPLACE = 3,
		API_STENCIL_OP_INCR_SAT = 4,
		API_STENCIL_OP_DECR_SAT = 5,
		API_STENCIL_OP_INVERT = 6,
		API_STENCIL_OP_INCR = 7,
		API_STENCIL_OP_DECR = 8
	} 	API_STENCIL_OP;

#define	API_DEFAULT_STENCIL_READ_MASK	( 0xff )
#define	API_DEFAULT_STENCIL_WRITE_MASK	( 0xff )

	typedef
		enum API_PRIMITIVE_TOPOLOGY
	{
		API_PRIMITIVE_TOPOLOGY_UNDEFINED = 0,
		API_PRIMITIVE_TOPOLOGY_POINTLIST = 1,
		API_PRIMITIVE_TOPOLOGY_LINELIST = 2,
		API_PRIMITIVE_TOPOLOGY_LINESTRIP = 3,
		API_PRIMITIVE_TOPOLOGY_TRIANGLELIST = 4,
		API_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = 5,
		API_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = 10,
		API_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = 11,
		API_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = 12,
		API_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = 13,
		API_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST = 33,
		API_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST = 34,
		API_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST = 35,
		API_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST = 36,
		API_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST = 37,
		API_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST = 38,
		API_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST = 39,
		API_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST = 40,
		API_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST = 41,
		API_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST = 42,
		API_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST = 43,
		API_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST = 44,
		API_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST = 45,
		API_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST = 46,
		API_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST = 47,
		API_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST = 48,
		API_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST = 49,
		API_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST = 50,
		API_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST = 51,
		API_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST = 52,
		API_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST = 53,
		API_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST = 54,
		API_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST = 55,
		API_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST = 56,
		API_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST = 57,
		API_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST = 58,
		API_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST = 59,
		API_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST = 60,
		API_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST = 61,
		API_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST = 62,
		API_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST = 63,
		API_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST = 64,
		API10_PRIMITIVE_TOPOLOGY_UNDEFINED = API_PRIMITIVE_TOPOLOGY_UNDEFINED,
		API10_PRIMITIVE_TOPOLOGY_POINTLIST = API_PRIMITIVE_TOPOLOGY_POINTLIST,
		API10_PRIMITIVE_TOPOLOGY_LINELIST = API_PRIMITIVE_TOPOLOGY_LINELIST,
		API10_PRIMITIVE_TOPOLOGY_LINESTRIP = API_PRIMITIVE_TOPOLOGY_LINESTRIP,
		API10_PRIMITIVE_TOPOLOGY_TRIANGLELIST = API_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
		API10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = API_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
		API10_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = API_PRIMITIVE_TOPOLOGY_LINELIST_ADJ,
		API10_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = API_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ,
		API10_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = API_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ,
		API10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = API_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ,
		API11_PRIMITIVE_TOPOLOGY_UNDEFINED = API_PRIMITIVE_TOPOLOGY_UNDEFINED,
		API11_PRIMITIVE_TOPOLOGY_POINTLIST = API_PRIMITIVE_TOPOLOGY_POINTLIST,
		API11_PRIMITIVE_TOPOLOGY_LINELIST = API_PRIMITIVE_TOPOLOGY_LINELIST,
		API11_PRIMITIVE_TOPOLOGY_LINESTRIP = API_PRIMITIVE_TOPOLOGY_LINESTRIP,
		API11_PRIMITIVE_TOPOLOGY_TRIANGLELIST = API_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
		API11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = API_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
		API11_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = API_PRIMITIVE_TOPOLOGY_LINELIST_ADJ,
		API11_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = API_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ,
		API11_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = API_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ,
		API11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = API_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ,
		API11_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST,
		API11_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST = API_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST
	} 	API_PRIMITIVE_TOPOLOGY;

	typedef
	enum API_SRV_DIMENSION
	{
		API_SRV_DIMENSION_UNKNOWN = 0,
		API_SRV_DIMENSION_BUFFER = 1,
		API_SRV_DIMENSION_TEXTURE1D = 2,
		API_SRV_DIMENSION_TEXTURE1DARRAY = 3,
		API_SRV_DIMENSION_TEXTURE2D = 4,
		API_SRV_DIMENSION_TEXTURE2DARRAY = 5,
		API_SRV_DIMENSION_TEXTURE2DMS = 6,
		API_SRV_DIMENSION_TEXTURE2DMSARRAY = 7,
		API_SRV_DIMENSION_TEXTURE3D = 8,
		API_SRV_DIMENSION_TEXTURECUBE = 9,
		API_SRV_DIMENSION_TEXTURECUBEARRAY = 10,
		API_SRV_DIMENSION_BUFFEREX = 11,
		API10_SRV_DIMENSION_UNKNOWN = API_SRV_DIMENSION_UNKNOWN,
		API10_SRV_DIMENSION_BUFFER = API_SRV_DIMENSION_BUFFER,
		API10_SRV_DIMENSION_TEXTURE1D = API_SRV_DIMENSION_TEXTURE1D,
		API10_SRV_DIMENSION_TEXTURE1DARRAY = API_SRV_DIMENSION_TEXTURE1DARRAY,
		API10_SRV_DIMENSION_TEXTURE2D = API_SRV_DIMENSION_TEXTURE2D,
		API10_SRV_DIMENSION_TEXTURE2DARRAY = API_SRV_DIMENSION_TEXTURE2DARRAY,
		API10_SRV_DIMENSION_TEXTURE2DMS = API_SRV_DIMENSION_TEXTURE2DMS,
		API10_SRV_DIMENSION_TEXTURE2DMSARRAY = API_SRV_DIMENSION_TEXTURE2DMSARRAY,
		API10_SRV_DIMENSION_TEXTURE3D = API_SRV_DIMENSION_TEXTURE3D,
		API10_SRV_DIMENSION_TEXTURECUBE = API_SRV_DIMENSION_TEXTURECUBE,
		API10_1_SRV_DIMENSION_UNKNOWN = API_SRV_DIMENSION_UNKNOWN,
		API10_1_SRV_DIMENSION_BUFFER = API_SRV_DIMENSION_BUFFER,
		API10_1_SRV_DIMENSION_TEXTURE1D = API_SRV_DIMENSION_TEXTURE1D,
		API10_1_SRV_DIMENSION_TEXTURE1DARRAY = API_SRV_DIMENSION_TEXTURE1DARRAY,
		API10_1_SRV_DIMENSION_TEXTURE2D = API_SRV_DIMENSION_TEXTURE2D,
		API10_1_SRV_DIMENSION_TEXTURE2DARRAY = API_SRV_DIMENSION_TEXTURE2DARRAY,
		API10_1_SRV_DIMENSION_TEXTURE2DMS = API_SRV_DIMENSION_TEXTURE2DMS,
		API10_1_SRV_DIMENSION_TEXTURE2DMSARRAY = API_SRV_DIMENSION_TEXTURE2DMSARRAY,
		API10_1_SRV_DIMENSION_TEXTURE3D = API_SRV_DIMENSION_TEXTURE3D,
		API10_1_SRV_DIMENSION_TEXTURECUBE = API_SRV_DIMENSION_TEXTURECUBE,
		API10_1_SRV_DIMENSION_TEXTURECUBEARRAY = API_SRV_DIMENSION_TEXTURECUBEARRAY,
		API11_SRV_DIMENSION_UNKNOWN = API_SRV_DIMENSION_UNKNOWN,
		API11_SRV_DIMENSION_BUFFER = API_SRV_DIMENSION_BUFFER,
		API11_SRV_DIMENSION_TEXTURE1D = API_SRV_DIMENSION_TEXTURE1D,
		API11_SRV_DIMENSION_TEXTURE1DARRAY = API_SRV_DIMENSION_TEXTURE1DARRAY,
		API11_SRV_DIMENSION_TEXTURE2D = API_SRV_DIMENSION_TEXTURE2D,
		API11_SRV_DIMENSION_TEXTURE2DARRAY = API_SRV_DIMENSION_TEXTURE2DARRAY,
		API11_SRV_DIMENSION_TEXTURE2DMS = API_SRV_DIMENSION_TEXTURE2DMS,
		API11_SRV_DIMENSION_TEXTURE2DMSARRAY = API_SRV_DIMENSION_TEXTURE2DMSARRAY,
		API11_SRV_DIMENSION_TEXTURE3D = API_SRV_DIMENSION_TEXTURE3D,
		API11_SRV_DIMENSION_TEXTURECUBE = API_SRV_DIMENSION_TEXTURECUBE,
		API11_SRV_DIMENSION_TEXTURECUBEARRAY = API_SRV_DIMENSION_TEXTURECUBEARRAY,
		API11_SRV_DIMENSION_BUFFEREX = API_SRV_DIMENSION_BUFFEREX
	} 	API_SRV_DIMENSION;

	typedef
	enum API_TextureType
	{
		API_Texture1D = 0x01,
		API_Texture2D = 0x02
	} API_TextureType;

	typedef
		enum API11_BLEND
	{
		API11_BLEND_ZERO = 1,
		API11_BLEND_ONE = 2,
		API11_BLEND_SRC_COLOR = 3,
		API11_BLEND_INV_SRC_COLOR = 4,
		API11_BLEND_SRC_ALPHA = 5,
		API11_BLEND_INV_SRC_ALPHA = 6,
		API11_BLEND_DEST_ALPHA = 7,
		API11_BLEND_INV_DEST_ALPHA = 8,
		API11_BLEND_DEST_COLOR = 9,
		API11_BLEND_INV_DEST_COLOR = 10,
		API11_BLEND_SRC_ALPHA_SAT = 11,
		API11_BLEND_BLEND_FACTOR = 14,
		API11_BLEND_INV_BLEND_FACTOR = 15,
		API11_BLEND_SRC1_COLOR = 16,
		API11_BLEND_INV_SRC1_COLOR = 17,
		API11_BLEND_SRC1_ALPHA = 18,
		API11_BLEND_INV_SRC1_ALPHA = 19
	} 	API11_BLEND;

	typedef
		enum API11_BLEND_OP
	{
		API11_BLEND_OP_ADD = 1,
		API11_BLEND_OP_SUBTRACT = 2,
		API11_BLEND_OP_REV_SUBTRACT = 3,
		API11_BLEND_OP_MIN = 4,
		API11_BLEND_OP_MAX = 5
	} 	API11_BLEND_OP;

	typedef struct API11_RENDER_TARGET_BLEND_DESC
	{
		BOOL BlendEnable;
		API11_BLEND SrcBlend;
		API11_BLEND DestBlend;
		API11_BLEND_OP BlendOp;
		API11_BLEND SrcBlendAlpha;
		API11_BLEND DestBlendAlpha;
		API11_BLEND_OP BlendOpAlpha;
		UINT8 RenderTargetWriteMask;
	} 	API11_RENDER_TARGET_BLEND_DESC;

	typedef
		enum API11_COLOR_WRITE_ENABLE
	{
		API11_COLOR_WRITE_ENABLE_RED = 1,
		API11_COLOR_WRITE_ENABLE_GREEN = 2,
		API11_COLOR_WRITE_ENABLE_BLUE = 4,
		API11_COLOR_WRITE_ENABLE_ALPHA = 8,
		API11_COLOR_WRITE_ENABLE_ALL = (((API11_COLOR_WRITE_ENABLE_RED | API11_COLOR_WRITE_ENABLE_GREEN) | API11_COLOR_WRITE_ENABLE_BLUE) | API11_COLOR_WRITE_ENABLE_ALPHA)
	} 	API11_COLOR_WRITE_ENABLE;

#define API10_SHADER_DEBUG                          (1 << 0)
#define API10_SHADER_SKIP_VALIDATION                (1 << 1)
#define API10_SHADER_SKIP_OPTIMIZATION              (1 << 2)
#define API10_SHADER_PACK_MATRIX_ROW_MAJOR          (1 << 3)
#define API10_SHADER_PACK_MATRIX_COLUMN_MAJOR       (1 << 4)
#define API10_SHADER_PARTIAL_PRECISION              (1 << 5)
#define API10_SHADER_FORCE_VS_SOFTWARE_NO_OPT       (1 << 6)
#define API10_SHADER_FORCE_PS_SOFTWARE_NO_OPT       (1 << 7)
#define API10_SHADER_NO_PRESHADER                   (1 << 8)
#define API10_SHADER_AVOID_FLOW_CONTROL             (1 << 9)
#define API10_SHADER_PREFER_FLOW_CONTROL            (1 << 10)
#define API10_SHADER_ENABLE_STRICTNESS              (1 << 11)
#define API10_SHADER_ENABLE_BACKWARDS_COMPATIBILITY (1 << 12)
#define API10_SHADER_IEEE_STRICTNESS                (1 << 13)
#define API10_SHADER_WARNINGS_ARE_ERRORS            (1 << 18)


	// optimization level flags
#define API10_SHADER_OPTIMIZATION_LEVEL0            (1 << 14)
#define API10_SHADER_OPTIMIZATION_LEVEL1            0
#define API10_SHADER_OPTIMIZATION_LEVEL2            ((1 << 14) | (1 << 15))
#define API10_SHADER_OPTIMIZATION_LEVEL3            (1 << 15)

}

#pragma warning(default : 4005)